SatNav: OSMNode Class Reference
OSMNode Class Reference
#include <osmnode.h>
Public Member Functions
OSMNode ()
OSMNode (int id, double lat, double lon, bool visible)
void setId (int id)
void setLat (double lat)
void setLon (double lon)
void setVisible (bool visible)
void setRelated (bool related)
int id ()
double x ()
double y ()
double lat ()
double lon ()
bool visible ()
bool related ()
Detailed Description
The OSMNode class is used to handle data relating to nodes on a map. This class is used for nodes such as POI's and Town/City markers, but is also used as part of the OSMWay and OSMRelation classes to hold the nodes that make up different ways and relations.
Definition at line 12 of file osmnode.h.
Constructor & Destructor Documentation
OSMNode::OSMNode ()
Create an empty OSMNode object
Definition at line 5 of file osmnode.cpp.
OSMNode::OSMNode (int id, double lat, double lon, bool visible)
Create an OSMNode object and initialise the members with the given values
Parameters:
id The numerical unique id of the node
lat The latitude of the node in degrees
lon The longitude of the node in degrees
visible True if the node should be visible on the map
Definition at line 9 of file osmnode.cpp.
References setLat(), and setLon().
Member Function Documentation
int OSMNode::id ()
Get the unique id of the node
Returns:
The unique id of the node
Definition at line 46 of file osmnode.cpp.
double OSMNode::lat ()
Get the latitude of the node
Returns:
The latitude of the node
Definition at line 51 of file osmnode.cpp.
double OSMNode::lon ()
Get the longitude of the node
Returns:
The longitude of the node
Definition at line 56 of file osmnode.cpp.
bool OSMNode::related ()
Get whether the node is related to a way or relation
Returns:
True if the node is related to a way or relation
Definition at line 76 of file osmnode.cpp.
void OSMNode::setId (int id)
Set the numerical unique id of the node
Parameters:
id The numerical unique id of the node
Definition at line 18 of file osmnode.cpp.
void OSMNode::setLat (double lat)
Set the latitude of the node
Parameters:
lat The latitude of the node
Definition at line 23 of file osmnode.cpp.
References Mercator::LatToY().
Referenced by OSMNode().
void OSMNode::setLon (double lon)
Set the longitude of the node
Parameters:
lon The longitude of the node
Definition at line 30 of file osmnode.cpp.
References Mercator::LonToX().
Referenced by OSMNode().
void OSMNode::setRelated (bool related)
Set whether the node is part of a way or relation. If it is related to a way or relation, it will be rendered on the map as part of that way or relation instead of independently as a POI
Parameters:
related True if the node is related to a way or relation
Definition at line 41 of file osmnode.cpp.
void OSMNode::setVisible (bool visible)
Set whether the node is visible on the map
Parameters:
visible True if the node should be visible on the map
Definition at line 36 of file osmnode.cpp.
bool OSMNode::visible ()
Get whether the node is shown on the map
Returns:
True if the node is visible
Definition at line 71 of file osmnode.cpp.
double OSMNode::x ()
Get the x position of the node
Returns:
The x position of the node
Definition at line 61 of file osmnode.cpp.
double OSMNode::y ()
Get the y position of the node
Returns:
The y position of the node
Definition at line 66 of file osmnode.cpp.
The documentation for this class was generated from the following files:
osmnode.h
osmnode.cpp