SatNav: OSMRelation Class Reference
OSMRelation Class Reference
#include <osmrelation.h>
Public Member Functions
OSMRelation (OSMMap *parent)
OSMRelation (OSMMap *parent, int id, bool visible)
void addMember (OSMRelationMember member)
void addMember (QXmlStreamReader &xml)
QList< OSMRelationMember > members ()
OSMRelationMember::Type getMemberType (OSMRelationMember member)
OSMRelationMember::Type getMemberType (int i)
OSMNode * getMemberNode (OSMRelationMember member)
OSMNode * getMemberNode (int i)
OSMWay * getMemberWay (OSMRelationMember member)
OSMWay * getMemberWay (int i)
void setId (int id)
void setVisible (bool visible)
void setRelated (bool related)
int id ()
bool visible ()
bool related ()
Detailed Description
The OSMRelation class is used to hold information about relations within an OSMMap. As the nodes and ways within a relation are stored only as id numbers, each instance of the OSMRelation class requires an OSMMap as its parent. This parent is used to get pointers to the OSMNode and OSMWay objects for each member.
Definition at line 17 of file osmrelation.h.
Constructor & Destructor Documentation
OSMRelation::OSMRelation (OSMMap * parent)
Create an empty OSMRelation object
Parameters:
parent The parent OSMMap object which the OSMRelation object is part of.
Definition at line 8 of file osmrelation.cpp.
OSMRelation::OSMRelation (OSMMap * parent, int id, bool visible)
Create an OSMRelation object with the specified unique id and visibility.
Parameters:
parent The parent OSMMap object which the OSMRelation object is part of.
id The numeric unique id of the relation
visible True if the relation should be visible on the map
Definition at line 13 of file osmrelation.cpp.
Member Function Documentation
void OSMRelation::addMember (QXmlStreamReader & xml)
Read an OSMRelationMember object from the given QXmlStreamReader object and add it to the relation. The xml stream needs to be at the start of a member element. (i.e. xml.isStartElement() && xml.name() == "member")
Parameters:
xml The QXmlStreamReader to be read from
Definition at line 41 of file osmrelation.cpp.
References addMember().
Referenced by addMember().
void OSMRelation::addMember (OSMRelationMember member)
Add a member to the relation.
Parameters:
member An OSMRelationMember object representing the member to be added.
Definition at line 21 of file osmrelation.cpp.
OSMNode * OSMRelation::getMemberNode (int i)
A convenience function, returns the OSMNode represented by members().at(i)
See also:
getMemberNode(OSMRelationMember)
Parameters:
i The index of the member
Returns:
The OSMNode represented my members().at(i)
Definition at line 75 of file osmrelation.cpp.
References getMemberNode().
OSMNode * OSMRelation::getMemberNode (OSMRelationMember member)
This function uses OSMMap::getNodeById() in the parent OSMMap to return a pointer to the OSMNode object referenced by the OSMRelationMember provided. This function should be used in conjunction with getMemberType() to make sure the OSMRelationMember you are requesting represents a node, rather than a way.
Parameters:
member The OSMRelationMember representing the OSMNode to be returned
Returns:
The OSMNode represented by member
Definition at line 67 of file osmrelation.cpp.
References OSMMap::getNodePtrById(), OSMRelationMember::ref(), and OSMRelationMember::type().
Referenced by getMemberNode().
OSMRelationMember::Type OSMRelation::getMemberType (int i)
Returns the type of the member at position i in the QList used to hold the members (the same QList returned my members()). This (or getMemberType(OSMRelationMember)) should be used before getMemberNode() or getMemberWay() to ensure you use the correct function to get the OSMNode or OSMWay.
Parameters:
i The position of the member within the QList
Returns:
The type of the member at position i (i.e. members().at(i).type())
Definition at line 62 of file osmrelation.cpp.
References getMemberType().
OSMRelationMember::Type OSMRelation::getMemberType (OSMRelationMember member)
Returns the type of the provided member. This (or getMemberType(int)) should be used before getMemberNode() or getMemberWay() to ensure you use the correct function to get the OSMNode or OSMWay.
Parameters:
member An OSMRelationMember object, the function will return the type of this object
Returns:
The type of the provided OSMRelationMember object
Definition at line 57 of file osmrelation.cpp.
References OSMRelationMember::type().
Referenced by getMemberType().
OSMWay * OSMRelation::getMemberWay (int i)
A convenience function, returns the OSMWay represented by members().at(i)
See also:
getMemberWay(OSMRelationMember)
Parameters:
i The index of the member
Returns:
The OSMWay represented my members().at(i)
Definition at line 88 of file osmrelation.cpp.
References getMemberWay().
OSMWay * OSMRelation::getMemberWay (OSMRelationMember member)
This function uses OSMMap::getWayById() in the parent OSMMap to return a pointer to the OSMWay object referenced by the OSMRelationMember provided. This function should be used in conjunction with getMemberType() to make sure the OSMRelationMember you are requesting represents a way, rather than a node.
Parameters:
member The OSMRelationMember representing the OSMWay to be returned
Returns:
The OSMWay represented by member
Definition at line 80 of file osmrelation.cpp.
References OSMMap::getWayPtrById(), OSMRelationMember::ref(), and OSMRelationMember::type().
Referenced by getMemberWay().
int OSMRelation::id ()
Returns the id of the relation
Returns:
The id of the relation
Definition at line 108 of file osmrelation.cpp.
QList< OSMRelationMember > OSMRelation::members ()
Return a QList containing all the members in the relation
Returns:
All the members in the relation
Definition at line 52 of file osmrelation.cpp.
bool OSMRelation::related ()
Returns true if the relation is part of another relation
Returns:
True if the realtion is related
Definition at line 118 of file osmrelation.cpp.
void OSMRelation::setId (int id)
Set the id of the relation
Parameters:
id The id of the realtion
Definition at line 93 of file osmrelation.cpp.
void OSMRelation::setRelated (bool related)
Set whether the relation is part of another relation
Parameters:
related True if the relation is related
Definition at line 103 of file osmrelation.cpp.
void OSMRelation::setVisible (bool visible)
Set the visibility of the relations members
Parameters:
visible True if the relation is to be shown on the map
Definition at line 98 of file osmrelation.cpp.
bool OSMRelation::visible ()
Returns true if the relation is to be shown on the map
Returns:
The visibility of the relation
Definition at line 113 of file osmrelation.cpp.
The documentation for this class was generated from the following files:
osmrelation.h
osmrelation.cpp