SatNav: Mercator Class Reference
Mercator Class Reference
#include <mercator.h>
Static Public Member Functions
static double LonToX (double lon)
static double XToLon (double x)
static double LatToY (double lat)
static double YToLat (double y)
Detailed Description
The Mercator class provides a number of static functinos for converting between degrees (latitude and longitude) and coordinates (x and y) for display on a map, using thte Guidermannian function.
Definition at line 12 of file mercator.h.
Member Function Documentation
static double Mercator::LatToY (double lat) [inline, static]
Converts latitude to a y coordinate
Parameters:
lat The latitude of the point to be converted
Returns:
The y coordinate for use in drawing a map
Definition at line 62 of file mercator.h.
Referenced by OSMNode::setLat(), OSMMap::setMaxLat(), and OSMMap::setMinLat().
static double Mercator::LonToX (double lon) [inline, static]
Converts longitude to an x coordinate
Parameters:
lon The longitude of the point to be converted
Returns:
The x coordinate for use in drawing a map
Definition at line 28 of file mercator.h.
Referenced by OSMNode::setLon(), OSMMap::setMaxLon(), and OSMMap::setMinLon().
static double Mercator::XToLon (double x) [inline, static]
Converts an x coordinate to longditude
Parameters:
x The x coordinate of the point to be converted
Returns:
The longitude of the point drawn on the map
Definition at line 45 of file mercator.h.
static double Mercator::YToLat (double y) [inline, static]
Converts a y coordinate to latditude
Parameters:
y The y coordinate of the point to be converted
Returns:
The latitude of the point drawn on the map
Definition at line 79 of file mercator.h.
The documentation for this class was generated from the following file:
mercator.h