SatNav: OSMRelationMember Class Reference
OSMRelationMember Class Reference
#include <osmrelationmember.h>
Public Types
enum Type { Node, Way }
Public Member Functions
OSMRelationMember ()
OSMRelationMember (Type a, int b)
OSMRelationMember (QXmlStreamReader &xml)
void setType (Type type)
void setRef (int ref)
Type type ()
int ref ()
OSMRelationMember readMember (QXmlStreamReader &xml)
Detailed Description
The OSMRelationMember class is used to store information about individual members within an OSMRelation object. The OSMRelationMember class is largely useless unless it is being used in conjunction with an OSMRelation and, in turn an OSMMap as only the id of a node or way is stored within the OSMRelationMember, and the OSMRelation and OSMMap are needed to get a pointer to the OSMNode or OSMWay object.
Definition at line 13 of file osmrelationmember.h.
Member Enumeration Documentation
enum OSMRelationMember::Type
Used to specify the type of a relation member
Definition at line 19 of file osmrelationmember.h.
Constructor & Destructor Documentation
OSMRelationMember::OSMRelationMember ()
Create an empty OSMRelationMember object
Definition at line 3 of file osmrelationmember.cpp.
OSMRelationMember::OSMRelationMember (Type a, int b)
Create an OSMRelationMember object with the given type and reference
Parameters:
a The type of the member
b The id number of the member
Definition at line 7 of file osmrelationmember.cpp.
OSMRelationMember::OSMRelationMember (QXmlStreamReader & xml)
Read an OSMRelationMember object from the given QXmlStreamReader object. The xml stream needs to be at the start of a member element. (i.e. xml.isStartElement() && xml.name() == "member")
Parameters:
xml The QXmlStreamReader to be read from
Definition at line 13 of file osmrelationmember.cpp.
References readMember().
Member Function Documentation
OSMRelationMember OSMRelationMember::readMember (QXmlStreamReader & xml)
Read the type and id number of the member from the specified XML stream. The xml stream needs to be at the start of a member element. (i.e. xml.isStartElement() && xml.name() == "member") A copy of the member is returned so that it can be used in other functions.
Parameters:
xml The XML stream to read from
Returns:
A copy of the OSMRelationMember after the XML data has been read.
Definition at line 38 of file osmrelationmember.cpp.
Referenced by OSMRelationMember().
int OSMRelationMember::ref ()
Returns the id of the member
Returns:
The reference id number of the member
Definition at line 33 of file osmrelationmember.cpp.
Referenced by OSMRelation::getMemberNode(), and OSMRelation::getMemberWay().
void OSMRelationMember::setRef (int ref)
Sets the id of the member
Parameters:
ref The reference id number
Definition at line 23 of file osmrelationmember.cpp.
void OSMRelationMember::setType (Type type)
Sets the type of the member
Parameters:
type The type of the member
Definition at line 18 of file osmrelationmember.cpp.
OSMRelationMember::Type OSMRelationMember::type ()
Returns the type of the member
Returns:
The type of the member
Definition at line 28 of file osmrelationmember.cpp.
Referenced by OSMRelation::getMemberNode(), OSMRelation::getMemberType(), and OSMRelation::getMemberWay().
The documentation for this class was generated from the following files:
osmrelationmember.h
osmrelationmember.cpp