SatNav: OSMMap Class Reference
OSMMap Class Reference
#include <osmmap.h>
Public Member Functions
OSMMap ()
void setMinLat (double minLat)
void setMaxLat (double maxLat)
void setMinLon (double minLon)
void setMaxLon (double maxLon)
double minLat ()
double maxLat ()
double minLon ()
double maxLon ()
double minX ()
double maxX ()
double minY ()
double maxY ()
void addNode (OSMNode node)
QList< OSMNode > nodes ()
OSMNode node (int id)
OSMNode * getNodePtrById (int id)
void addWay (OSMWay way)
QList< OSMWay > ways ()
OSMWay way (int id)
OSMWay * getWayPtrById (int id)
void addRelation (OSMRelation relation)
QList< OSMRelation > relations ()
OSMRelation relation (int id)
OSMRelation * getRelationPtrById (int id)
void paint (QPainter *painter)
void zoomIn (int steps=1)
void zoomOut (int steps=1)
void zoom (int level)
Detailed Description
The OSMMap class holds all nodes, ways and relations representing an area.
Definition at line 16 of file osmmap.h.
Constructor & Destructor Documentation
OSMMap::OSMMap ()
Create an empty Map
Definition at line 8 of file osmmap.cpp.
Member Function Documentation
void OSMMap::addNode (OSMNode node)
Add an OSMNode object to the map
Parameters:
node An OSMNode object representing the node the be added.
Definition at line 28 of file osmmap.cpp.
void OSMMap::addRelation (OSMRelation relation)
Add an OSMRelation object to the map
Parameters:
relation An OSMRelation object representing the node the be added.
Definition at line 80 of file osmmap.cpp.
void OSMMap::addWay (OSMWay way)
Add an OSMWay object to the map
Parameters:
way An OSMWay object representing the node the be added.
Definition at line 54 of file osmmap.cpp.
OSMNode * OSMMap::getNodePtrById (int id)
Returns pointer to the node with the ID specified. Unlike node(), this function matches the specified id to OSMNode::m_id rather than the position in the list. This function is used primarily to add a node to a way or relation, be aware that, as it is a pointer, any changes made to the returned object will be relflected in the OSMMap object.
See also:
nodes()
node(int)
Parameters:
id The id of the node to return
Returns:
A pointer to the requested OSMNode
Definition at line 43 of file osmmap.cpp.
Referenced by OSMRelation::getMemberNode().
OSMRelation * OSMMap::getRelationPtrById (int id)
Returns pointer to the relation with the ID specified. Unlike relation(), this function matches the specified id to OSMRelation::m_id rather than the position in the list. This function is used primarily to add a relation to another relation, be aware that, as it is a pointer, any changes made to the returned object will be relflected in the OSMMap object.
See also:
relations()
relation(int)
Parameters:
id The id of the relation to return
Returns:
A pointer to the requested OSMRelation
Definition at line 95 of file osmmap.cpp.
OSMWay * OSMMap::getWayPtrById (int id)
Returns pointer to the way with the ID specified. Unlike way(), this function matches the specified id to OSMWay::m_id rather than the position in the list. This function is used primarily to add a way to a relation, be aware that, as it is a pointer, any changes made to the returned object will be relflected in the OSMMap object.
See also:
ways()
way(int)
Parameters:
id The id of the way to return
Returns:
A pointer to the requested OSMWay
Definition at line 69 of file osmmap.cpp.
Referenced by OSMRelation::getMemberWay().
double OSMMap::maxLat ()
Return the maximum latitude of the map
Returns:
The maximum latitude of the map
Definition at line 19 of file osmmap.cpp.
double OSMMap::maxLon ()
Return the maximum longitude of the map
Returns:
The maximum longitude of the map
Definition at line 21 of file osmmap.cpp.
double OSMMap::maxX ()
Return the maximum x coordinate of the map
Returns:
The maximum x coordinate of the map
Definition at line 24 of file osmmap.cpp.
double OSMMap::maxY ()
Return the maximum y coordinate of the map
Returns:
The maximum y coordinate of the map
Definition at line 26 of file osmmap.cpp.
double OSMMap::minLat ()
Return the minimum latitude of the map
Returns:
The minimum latitude of the map
Definition at line 18 of file osmmap.cpp.
double OSMMap::minLon ()
Return the minimum longitude of the map
Returns:
The minimum longitude of the map
Definition at line 20 of file osmmap.cpp.
double OSMMap::minX ()
Return the minimum x coordinate of the map
Returns:
The minimum x coordinate of the map
Definition at line 23 of file osmmap.cpp.
double OSMMap::minY ()
Return the minimum y coordinate of the map
Returns:
The minimum y coordinate of the map
Definition at line 25 of file osmmap.cpp.
OSMNode OSMMap::node (int id)
Return the node at position id in the list of nodes. Equivalent to nodes().at(id).
See also:
nodes()
getNodePtrById(int)
Parameters:
id The position of the node within the QList
Returns:
An OSMNode object representing the node at position id.
Definition at line 38 of file osmmap.cpp.
QList< OSMNode > OSMMap::nodes ()
Return all nodes in the map as a QList. Be aware that for large maps, this list can be very large, so take care when using. Use getNodePtrById(int) or node(int) if you need just one node.
See also:
getNodePtrById(int)
node(int)
Returns:
A QList<OSMNode> containing all the nodes in the map
Definition at line 33 of file osmmap.cpp.
void OSMMap::paint (QPainter * painter)
Draws the map to the provided QPainter
Parameters:
painter The QPainter to draw the map to
Definition at line 106 of file osmmap.cpp.
References ways().
OSMRelation OSMMap::relation (int id)
Return the relation at position id in the list of relations. Equivalent to relations().at(id).
See also:
relations()
getRelationPtrById(int)
Parameters:
id The position of the relation within the QList
Returns:
An OSMRelation object representing the relation at position id.
Definition at line 90 of file osmmap.cpp.
QList< OSMRelation > OSMMap::relations ()
Return all relations in the map as a QList. Be aware that for large maps, this list can be very large, so take care when using. Use getRelationPtrById(int) or relation(int) if you need just one node.
See also:
getRelationPtrById(int)
relation(int)
Returns:
A QList<OSMNode> containing all the relations in the map
Definition at line 85 of file osmmap.cpp.
void OSMMap::setMaxLat (double maxLat)
Set the maximum latitude of the map
Parameters:
maxLat The maximum latitude of the map
Definition at line 14 of file osmmap.cpp.
References Mercator::LatToY().
void OSMMap::setMaxLon (double maxLon)
Set the maximum longitude of the map
Parameters:
maxLon The maximum longitude of the map
Definition at line 16 of file osmmap.cpp.
References Mercator::LonToX().
void OSMMap::setMinLat (double minLat)
Set the minimum latitude of the map
Parameters:
minLat The minimum latitude of the map
Definition at line 13 of file osmmap.cpp.
References Mercator::LatToY().
void OSMMap::setMinLon (double minLon)
Set the minimum longitude of the map
Parameters:
minLon The minimum longitude of the map
Definition at line 15 of file osmmap.cpp.
References Mercator::LonToX().
OSMWay OSMMap::way (int id)
Return the way at position id in the list of ways. Equivalent to ways().at(id).
See also:
ways()
getWayPtrById(int)
Parameters:
id The position of the way within the QList
Returns:
An OSMWay object representing the way at position id.
Definition at line 64 of file osmmap.cpp.
QList< OSMWay > OSMMap::ways ()
Return all ways in the map as a QList. Be aware that for large maps, this list can be very large, so take care when using. Use getWayPtrById(int) or way(int) if you need just one node.
See also:
getWayPtrById(int)
way(int)
Returns:
A QList<OSMWay> containing all the ways in the map
Definition at line 59 of file osmmap.cpp.
Referenced by paint().
void OSMMap::zoom (int level)
Zooms the map to the specified zoom level
Parameters:
level The level to zoom to
Definition at line 126 of file osmmap.cpp.
void OSMMap::zoomIn (int steps = 1)
Zooms the map in the specified number of steps.
Parameters:
steps The number of steps to zoom. Defaults to 1
Definition at line 116 of file osmmap.cpp.
void OSMMap::zoomOut (int steps = 1)
Zooms the map out the specified number of steps.
Parameters:
steps The number of steps to zoom. Defaults to 1
Definition at line 121 of file osmmap.cpp.
The documentation for this class was generated from the following files:
osmmap.h
osmmap.cpp